# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c79930729bdfc48bff19301606212fc545377473a7547abc5ae86e53d91bea2a0d0e44a83a801ba4923b69bc76d972ee013aa82d70a94948b410c3b41422fa7a

test:
  secret_key_base: 7bc2f0221bf715469fd405bbb771fe6e11019bec7176867ce882b961851f5d06d7d494982f49ddf81b681443fc6315c2d39f6efc24def1b2c0696135ac423297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
